services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      NODE_ENV: development
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: user_management
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data: