
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: basededatosinit
    ports:
      - "3307:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db